apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-system
spec:
  destination:
    name: 'minikube'
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.crossplane.io/stable'
    targetRevision: 1.14.5
    chart: crossplane
  sources: []
  project: default
